use pointers instead of members to query display attributes
Fixes the following building errors:

hardware/intel/hwcomposer/hwcomposer.cpp: In function 'int hwc_get_display_attrs(hwc_composer_device_1*, int, uint32_t, const uint32_t*, int32_t*)':
hardware/intel/hwcomposer/hwcomposer.cpp:197:33: error: request for member 'mode' in 'drm->gralloc_drm_t::primary', which is of pointer type 'gralloc_drm_output*' (maybe you meant to use '->' ?)
hardware/intel/hwcomposer/hwcomposer.cpp:200:33: error: request for member 'mode' in 'drm->gralloc_drm_t::primary', which is of pointer type 'gralloc_drm_output*' (maybe you meant to use '->' ?)
hardware/intel/hwcomposer/hwcomposer.cpp:203:33: error: request for member 'mode' in 'drm->gralloc_drm_t::primary', which is of pointer type 'gralloc_drm_output*' (maybe you meant to use '->' ?)
hardware/intel/hwcomposer/hwcomposer.cpp:206:33: error: request for member 'xdpi' in 'drm->gralloc_drm_t::primary', which is of pointer type 'gralloc_drm_output*' (maybe you meant to use '->' ?)
hardware/intel/hwcomposer/hwcomposer.cpp:209:33: error: request for member 'ydpi' in 'drm->gralloc_drm_t::primary', which is of pointer type 'gralloc_drm_output*' (maybe you meant to use '->' ?)
build/core/binary.mk:432: recipe for target 'out/target/product/x86/obj/SHARED_LIBRARIES/hwcomposer.x86_intermediates/hwcomposer.o' failed
make: *** [out/target/product/x86/obj/SHARED_LIBRARIES/hwcomposer.x86_intermediates/hwcomposer.o] Error 1
make: *** Waiting for unfinished jobs....